name: Cleanup

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  cleanup_gh_pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          
      - name: Cleanup reports folder
        shell: bash
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}

          cd reports
          cd $BRANCH_NAME
          
          rm -rf *
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "Deleting $BRANCH_NAME folder contents."
          git push origin
