on:
  pull_request:
    types:
      - closed

jobs:
  Cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          
      - name: Cleanup reports
        shell: bash
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}

          cd reports
          cd $BRANCH_NAME
          
          rm -rf *
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "Deleting ${{ github.head_ref || github.ref_name }} folder contents."
          git push origin
