on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Delete reports
        run: |
          git fetch
          git checkout gh-pages
          cd reports
          cd ${{ github.head_ref || github.ref_name }}
          rm -rf *
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git status
          git commit -m "Deleting ${{ github.head_ref || github.ref_name }} folder contents."
          git push
